inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - !ruby/regexp /old_and_unused\.rb$/

  Rails:
    enabled: true

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# 「and」「or」の使用を許可
AndOr:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# {}のスペースがあることをチェック
Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

# 本文の周りに空の行はないかチェック
Layout/EmptyLinesAroundClassBody:
  Enabled: true

# メソッド定義の周りに空の行はないかチェック
Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# モジュール定義の周りに空の行がないかチェック
Layout/EmptyLinesAroundModuleBody:
  Enabled: true


# 以下検査で警告出る為記述、行の文字数制限などは改善策見つかり次第改善する

# 空のメソッドを一行で記述しなくても許可
Style/EmptyMethod:
  Enabled: false

# ブロックの行が長くても許可
Metrics/BlockLength:
  Enabled: false

# 1行あたりの文字数を120文字まで許可
LineLength:
  Max: 120

# AbcSizeチェックの基準値を20に変更
Metrics/AbcSize:
  Max: 20

# 複数行ステートメントの修飾子句を許可
Style/MultilineIfModifier:
  Enabled: false
