version: '3'
services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - .:/cocktail-hub

  web:
    build: .
    command: bin/server
    volumes:
      - .:/cocktail-hub:cached
      - /cocktail-hub/vendor
      - /cocktail-hub/tmp
      - /cocktail-hub/log
      - /cocktail-hub/.git
    ports:
      - "3000:3000"
      - "3035:3035"
    stdin_open: true
    tty: true
    depends_on:
      - db