default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: cocktail_hub_development

test:
  <<: *default
  database: cocktail_hub_test

production:
  <<: *default
  database: cocktail_hub_production
  username: cocktail_hub
  password: <%= ENV['COCKTAIL_HUB_DATABASE_PASSWORD'] %>

production:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  database: cocktail_hub_production
  username: root
  password: password
  host: cocktail-hub-db.cbehruninhnb.ap-northeast-1.rds.amazonaws.com
  port: 3306
  socket: /var/lib/mysql/mysql.sock